version: "3.8"

services:
  mysql:
    image: 'mysql:5.7'
    container_name: mysql
    environment:
      - MYSQL_DATABASE=transform
      - MYSQL_ROOT_PASSWORD=qwer1234
      - MYSQL_USER=transformer
      - MYSQL_PASSWORD=qwer1234
      - MYSQL_DIRECTORY="/var/lib/mysql"
    ports:
      - '3306:3306'
    volumes:
      - './configs/mysql:/docker-entrypoint-initdb.d/'
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  zookeeper:
    container_name: zookeeper
    image: 'wurstmeister/zookeeper:3.4.6'
    ports:
      - '2181:2181'

  kafka:
    container_name: kafka1
    image: 'wurstmeister/kafka:2.12-2.3.0'
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "sdk:5:1"
    depends_on:
      - zookeeper
